trigger:
  branches:
    include: ["master"]
  paths:
    exclude: [".github", "doc", "*.md"]

jobs:
- job: Windows
  displayName: Windows
  continueOnError: "true"
  strategy:
    matrix:
      Debug:
        buildConfiguration: "Debug"
      Release:
        buildConfiguration: "Release"
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: build.yml
  
- job: macOS
  displayName: macOS
  continueOnError: "true"
  strategy:
    matrix:
      Debug:
        buildConfiguration: "Debug"
      Release:
        buildConfiguration: "Release"
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: build.yml

- job: Linux
  displayName: Linux
  continueOnError: "true"
  strategy:
    matrix:
      Debug:
        buildConfiguration: "Debug"
      Release:
        buildConfiguration: "Release"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: build.yml
