trigger:
  branches:
    include: ["master", "*_validate"]
  paths:
    exclude: [".github", "doc", "*.md"]

jobs:
- job: Windows
  displayName: Windows
  continueOnError: 'true'
  strategy:
    matrix:
      Debug:
        buildConfiguration: "Debug"
      Release:
        buildConfiguration: "Release"
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build.yml
  - task: CopyFiles@2
    displayName: Collect packages
    inputs:
      SourceFolder: bin\$(BuildConfiguration)\Packages
      Contents: |
        *.nupkg
        *.snupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)\Packages
    condition: eq(variables['BuildConfiguration'], 'Release')
  - task: PublishBuildArtifacts@1
    displayName: Publish packages as build artifacts
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\Packages
      ArtifactName: Packages
      publishLocation: Container
    condition: eq(variables['BuildConfiguration'], 'Release')
  - task: CopyFiles@2
    displayName: Collect dump
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: '**\*.dmp'
      TargetFolder: $(Build.ArtifactStagingDirectory)\Dumps
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: Publish dumps
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\Dumps
      ArtifactName: Dumps
      publishLocation: Container
    condition: always()